language: node_js
node_js:
  - 6
before_script:
  - npm prune
script:
  - npm run build
  - npm run test
  - npm run generate
deploy:
  provider: script
  script: npm run publish
  skip_cleanup: true
  on:
    branch: master
