language: node_js
node_js:
- 4
before_script:
- npm prune
script:
- npm test
deploy:
  provider: npm
  on:
    repo: wikiwi/typeless
    tags: true
    node: 4
  email: vinh@wikiwi.io
  api_key:
    secure: ajn1F6j1MSmc7anHkZSQBVhQhFliS5nufYWxck85UJ4hA0x2PGvJL+Suc8Zuu9+DG069dgMUKHXlcg7qby7VQ/FjdZLqrXiA6/EqAPYQbymN+hvdcXVtl9nXdZBgaJ/8zR+uzOv61XmUQ216zGH3eG7wCAGVmBs9VKWs8wug7NXhw1UBA0SwPRC6rHuBsbYh5NWtClaPAk6YI6QzJQa0ztW2z6jwAJ2hULG92YvtoXgFzl45yzHJYZ5nxafUL5CbLF8MDiTC9LOg/lcREvchgovETm/1Ht9vc3AWkqEY62tk6mv0sJN1yIgLpgzVf9GPiVw2f4GMlyj2orIyQ0q3z0K4+WzFRMo8Kw//OF6a/crwoKIL83nKGpdQeMCNvdKCoaX6ugXSxlBC9pUNbBribh0Vdd/9UBgHAinKLA7keIX1qK2ITJVZ5KWvIlyPL1X03/v4+Pj8EMD5G6Rab+RkeI/98v997lv8NsNfDdQ5X/tHDATh/1tK4m9z+yk2tqMy0y9zA1SPTqQfhNGFOuP9YWAE1PL1IPSKyLD38Rr2gVtjhZLJLxhCo/Lo2FzEtybuBpftEtIjeIesY+0NctladFlKXXF3nyKRZSipRRcu6em/hMQdtstPRlDehTN9LOObIeWfP0roK3FRsaLwX4gz889Z2kOQ75C9iWHhv8qE6s8=
